### ISSUE TITLE
Incorrect rat picture??????

### ISSUE THREAD

**Issue by Snapperoney** [risc15/Facility15Test#1]
uhhhhh, admin. there's a weird picture???? in the rat folder??????

can someone please look into this????

**Comment by risc15** [comment]
Looked into it. Seems fine here? Post a picture of the problem if you can; it may be on your end.

**Comment by Snapperoney** [comment]
l-
l-
l-
like uhhhhhhhh.
*blushes*
a g-
g-
g-
g-
g-
gif??????

**Comment by risc15** [comment]
Sweetie.
I need a picture for you to prove this. I looked at the pictures and see nothing but rats.

**Comment by Snapperoney** [comment]
ok hang on i need my moms *phone

**Comment by Snapperoney** [comment]
![Screenshot 2021-08-29 233353](https://user-images.githubusercontent.com/74995220/131285593-999a85e3-183c-4630-b830-6fa1c84b1202.png)

**Comment by Snapperoney** [comment]
there

**Comment by Zatch-z** [comment]
thank you for pointing this out. will fix asap

**Comment by risc15** [comment]
*Looks closely*

I THINK I see the problem. Will look into it, thanks, team.

**Comment by Zatch-z** [comment]
fixed, good work team

**Comment by Snapperoney** [comment]
ok guess ill just....

**Comment by risc15** [comment]
Don't think so. I'll be the one closing it.

**Comment by Snapperoney** [comment]
i-
i-
i-
i-
im very sorrry 😢
